# Generated by Django 5.0 on 2025-06-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WitsNote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='witsnote_post',
        ),
    ]
