# Generated by Django 5.0 on 2025-07-05 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitsNote', '0002_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conclusion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
