# Generated by Django 5.0 on 2025-07-17 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitsNote', '0005_postimage_remove_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='WitsNote.post'),
            preserve_default=False,
        ),
    ]
