# Generated by Django 5.0 on 2025-08-11 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitsNote', '0006_postimage_image_postimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Standard', 'standard'), ('Case Study', 'case_study'), ('Listicle', 'listicle'), ('Infographic', 'infographic')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
