# Generated by Django 5.0 on 2025-08-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitsNote', '0007_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Standard', 'standard'), ('Case Study', 'case_study'), ('Listicle', 'listicle'), ('Infographic', 'infographic')], default='Standard', max_length=50),
        ),
    ]
