# Generated by Django 5.0 on 2025-09-25 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitsNote', '0008_alter_post_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListicleSubheading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subheadings', to='WitsNote.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
