# Generated by Django 5.0 on 2025-09-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitsNote', '0009_listiclesubheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='listiclesubheading',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='listiclesubheading',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
