# Generated by Django 5.0 on 2025-09-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitsNote', '0010_listiclesubheading_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfographicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infographic_sections', to='WitsNote.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
