# Generated by Django 5.0 on 2025-09-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitsNote', '0011_infographicsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conclusion',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(default='', null=True),
        ),
    ]
