# Generated by Django 5.0 on 2025-09-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitsNote', '0012_alter_post_conclusion_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conclusion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
