# Generated by Django 5.0 on 2025-09-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WitsNote', '0013_alter_post_conclusion_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
