# Generated by Django 5.0 on 2025-06-05 15:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(help_text='Comma-separated skills (e.g. Python, Django, REST)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_link',
            field=models.URLField(help_text='Link to portfolio or LinkedIn'),
        ),
    ]
