# Generated by Django 5.0 on 2025-09-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_postcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='users_userprofile',
        ),
    ]
