# Generated by Django 5.0 on 2025-09-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_profile_picture_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work_link',
            field=models.URLField(default='', help_text='Link to portfolio or LinkedIn'),
        ),
    ]
