# Generated by Django 5.0 on 2025-09-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_work_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work_link',
            field=models.URLField(default=list, help_text='Link to portfolio or LinkedIn'),
        ),
    ]
