# Generated by Django 5.0 on 2025-09-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_work_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work_link',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
