# Generated by Django 5.0 on 2025-09-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofile_work_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work_link',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
